import type { Template } from "./App";

export const CLIENTS: Record<string, Template> = {
  "mona-islam": {
    id: "mona-islam",
    name: "منى وإسلام",
    nameEn: "Mona & Islam",
    category: "كلاسيك",
    tags: ["كلاسيك"],
    image: "/pic2.jpg",
    backgroundVideo: "/vid2.mp4",
    accent: "#b49667",
    description: "",
    details: {
      firstName: "إسلام",
      secondName: "منى",
      dateLine: "الخميس · 12 ديسمبر 2028 · 16:00",
      day: "12",
      month: "ديسمبر",
      year: "2028",
      weekday: "الخميس",
      time: "16:00",
      venueTitle: ["مسجد", "السداد"],
      address: ["قاعة المسجد الرئيسية", "المملكة العربية السعودية"],
      closing: "بكل الحب، إسلام ومنى",
      countdownDate: new Date("2028-12-12T16:00:00"),
    },
  },

  "omar-hisham": {
    id: "omar-hisham",
    name: "عمر وهشام",
    nameEn: "Omar & Hisham",
    category: "كلاسيك",
    tags: ["كلاسيك"],
    image: "/a2.png",
    accent: "#c5a261",
    description: "",
    details: {
      firstName: "عمر",
      secondName: "هشام",
      dateLine: "الأربعاء · 30 سبتمبر 2026 · 17:00",
      day: "30",
      month: "سبتمبر",
      year: "2026",
      weekday: "الأربعاء",
      time: "17:00",
      venueTitle: ["قهوة", "الديوان"],
      address: ["عين شمس الدولة", ""],
      closing: "بكل الحب، عمر وهشام",
      countdownDate: new Date("2026-09-30T17:00:00"),
    },
  },
};